// mumuspec console — 生成 Spec 可视化控制台 HTML
const fs = require('fs');
const path = require('path');
const { resolveDir, readSpec } = require('../utils');

module.exports = function(args) {
  const specDir = resolveDir(args[0] || 'specs');
  const outputPath = path.resolve(args[1] || 'spec-console.html');

  if (!fs.existsSync(specDir)) { console.error('❌ 目录不存在: ' + specDir); process.exit(1); }

  const docs = [];
  for (let i = 1; i <= 14; i++) {
    const content = readSpec(specDir, i);
    const titleMatch = content ? content.match(/^#\s*\d*\s*[—\-−]\s*(.+)/m) : null;
    docs.push({ num: i, title: titleMatch ? titleMatch[1].trim() : '—', status: content ? (content.replace(/#.*\n?/g,'').replace(/>.*\n?/g,'').trim().length > 50 ? 'filled' : 'empty') : 'missing' });
  }
  const filled = docs.filter(d => d.status === 'filled').length;

  const html = `<!DOCTYPE html><html lang="zh-CN">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Spec Console — ${path.basename(path.resolve(specDir))}</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}body{font-family:"PingFang SC",-apple-system,sans-serif;color:#1a1a1a;background:#f8f8f5;line-height:1.6}
.topbar{position:sticky;top:0;z-index:10;background:rgba(248,248,245,0.88);backdrop-filter:blur(10px);border-bottom:1px solid #e4e4e0;padding:14px 32px;display:flex;align-items:center;justify-content:space-between}
.topbar h1{font-size:16px;font-weight:650;color:#111}.topbar .badge{font-size:12px;padding:4px 10px;border-radius:12px;background:#e8f5e8;color:#3a8a3a}
.page{max-width:1200px;margin:0 auto;padding:32px}
.progress-wrap{margin-bottom:32px;background:#fff;border:1px solid #e4e4e0;border-radius:8px;padding:20px 24px;display:flex;align-items:center;gap:20px}
.progress-bar{flex:1;height:8px;background:#f0f0ed;border-radius:4px;overflow:hidden}.progress-fill{height:100%;background:#d94f4f;border-radius:4px;transition:width .5s}
.progress-text{font-size:14px;font-weight:650;color:#111;white-space:nowrap}
.doc-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:2px;background:#e4e4e0;border:1px solid #e4e4e0;border-radius:8px;overflow:hidden}
.doc-card{background:#fff;padding:18px 20px}.doc-card h3{font-size:13px;font-weight:650;color:#111;margin-bottom:4px}
.dc-status{font-size:10px;padding:2px 6px;border-radius:3px;font-weight:600;display:inline-block;margin-bottom:6px}
.dc-status.filled{background:#e8f5e8;color:#3a8a3a}.dc-status.empty{background:#fef3f3;color:#d94f4f}.dc-status.missing{background:#f5f5f5;color:#ccc}
.footer{text-align:center;padding:40px 0;border-top:1px solid #e4e4e0;margin-top:32px}.footer p{font-size:11px;color:#ccc}
@media(max-width:768px){.doc-grid{grid-template-columns:1fr}}
</style></head>
<body>
<nav class="topbar"><h1>Spec Console</h1><span class="badge">${filled}/14 份已填写</span></nav>
<div class="page">
<div class="progress-wrap"><div class="progress-bar"><div class="progress-fill" style="width:${Math.round(filled/14*100)}%"></div></div><div class="progress-text">${filled}/14</div></div>
<div class="doc-grid">
${docs.map(d => `<div class="doc-card"><h3>${String(d.num).padStart(2,'0')} — ${d.title}</h3><span class="dc-status ${d.status}">${d.status==='filled'?'✅ 已填写':d.status==='empty'?'⚠️ 内容空':'❌ 文件缺失'}</span></div>`).join('')}
</div></div>
<footer class="footer"><p>Generated by MumuSpec CLI · <a href="https://mumucoding.com" style="color:#aaa">mumucoding.com</a></p></footer>
</body></html>`;
  fs.writeFileSync(outputPath, html, 'utf-8');
  console.log('✨ Spec Console 已生成: ' + outputPath);
  console.log('📊 ' + filled + '/14 份已填写');
};
